<Type Name="FirstChanceExceptionEventArgs" FullName="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="bc000b362500be8011240d0d707c1d0845fb913c" />
    <Meta Name="ms.sourcegitcommit" Value="434f60616a9793fa8436744549fc856e94f7a648" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="fr-FR" />
    <Meta Name="ms.lasthandoff" Value="08/25/2018" />
    <Meta Name="ms.locfileid" Value="39993652" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi beforefieldinit FirstChanceExceptionEventArgs extends System.EventArgs" />
  <TypeSignature Language="DocId" Value="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" />
  <TypeSignature Language="VB.NET" Value="Public Class FirstChanceExceptionEventArgs&#xA;Inherits EventArgs" />
  <TypeSignature Language="C++ CLI" Value="public ref class FirstChanceExceptionEventArgs : EventArgs" />
  <TypeSignature Language="F#" Value="type FirstChanceExceptionEventArgs = class&#xA;    inherit EventArgs" />
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.EventArgs</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>
      <span data-ttu-id="c2e36-101">Fournit des données pour l'événement de notification qui se déclenche lorsqu'une exception managée se produit pour la première fois, avant que le Common Language Runtime ne commence à rechercher des gestionnaires d'événements.</span>
      <span class="sxs-lookup">
        <span data-stu-id="c2e36-101">Provides data for the notification event that is raised when a managed exception first occurs, before the common language runtime begins searching for event handlers.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c2e36-102">Cette classe fournit le Gestionnaire d’exceptions pour le <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> événement avec un accès à l’exception.</span><span class="sxs-lookup"><span data-stu-id="c2e36-102">This class provides the exception handler for the <xref:System.AppDomain.FirstChanceException?displayProperty=nameWithType> event with access to the exception.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c2e36-103">L’exemple suivant crée une série de domaines d’application nommé `Child_0` via `Child_3`, avec un `Worker` objet dans chaque domaine d’application.</span><span class="sxs-lookup"><span data-stu-id="c2e36-103">The following example creates a series of application domains named `Child_0` through `Child_3`, with a `Worker` object in each application domain.</span></span> <span data-ttu-id="c2e36-104">Chaque `Worker` objet a une référence à la `Worker` de l’objet dans le domaine d’application suivant, à l’exception de la `Worker` dans le dernier domaine d’application.</span><span class="sxs-lookup"><span data-stu-id="c2e36-104">Each `Worker` object has a reference to the `Worker` object in the next application domain, except for the `Worker` in the last application domain.</span></span> <span data-ttu-id="c2e36-105">Le <xref:System.AppDomain.FirstChanceException> événement est géré dans tous les domaines d’application à l’exception `Child_1`.</span><span class="sxs-lookup"><span data-stu-id="c2e36-105">The <xref:System.AppDomain.FirstChanceException> event is handled in all application domains except `Child_1`.</span></span>  
  
 <span data-ttu-id="c2e36-106">Lorsque les domaines d’application ont été créées, le domaine d’application par défaut appelle la `TestException` méthode pour le premier domaine d’application enfant.</span><span class="sxs-lookup"><span data-stu-id="c2e36-106">When the application domains have been created, the default application domain calls the `TestException` method for the first child application domain.</span></span> <span data-ttu-id="c2e36-107">Chaque `Worker` object appelle le `TestException` méthode pour le suivant, jusqu'à ce que le dernier `Worker` lève une exception qui est gérée ou non prise en charge.</span><span class="sxs-lookup"><span data-stu-id="c2e36-107">Each `Worker` object calls the `TestException` method for the next, until the last `Worker` throws an exception that is either handled or unhandled.</span></span> <span data-ttu-id="c2e36-108">Par conséquent, le thread actuel traverse tous les domaines d’application, et `TestException` est ajouté à la pile dans chaque domaine d’application.</span><span class="sxs-lookup"><span data-stu-id="c2e36-108">Thus, the current thread passes through all the application domains, and `TestException` is added to the stack in each application domain.</span></span>  
  
 <span data-ttu-id="c2e36-109">Lors de la dernière `Worker` objet gère l’exception, le <xref:System.AppDomain.FirstChanceException> événement est déclenché uniquement dans le dernier domaine d’application.</span><span class="sxs-lookup"><span data-stu-id="c2e36-109">When the last `Worker` object handles the exception, the <xref:System.AppDomain.FirstChanceException> event is raised only in the last application domain.</span></span> <span data-ttu-id="c2e36-110">Les autres domaines d’application aucune chance pour gérer l’exception, donc l’événement n’est pas déclenché.</span><span class="sxs-lookup"><span data-stu-id="c2e36-110">The other application domains never get a chance to handle the exception, so the event is not raised.</span></span>  
  
 <span data-ttu-id="c2e36-111">Lors de la dernière `Worker` objet ne gère pas l’exception, le <xref:System.AppDomain.FirstChanceException> événement est déclenché dans chaque domaine d’application qui a un gestionnaire d’événements.</span><span class="sxs-lookup"><span data-stu-id="c2e36-111">When the last `Worker` object does not handle the exception, the <xref:System.AppDomain.FirstChanceException> event is raised in each application domain that has an event handler.</span></span> <span data-ttu-id="c2e36-112">À l’issue de chaque gestionnaire d’événements, la pile continue à dérouler jusqu'à ce que l’exception est interceptée par le domaine d’application par défaut.</span><span class="sxs-lookup"><span data-stu-id="c2e36-112">After each event handler has finished, the stack continues to unwind until the exception is caught by the default application domain.</span></span>  
  
> [!NOTE]
>  <span data-ttu-id="c2e36-113">Pour voir comment l’affichage de la pile augmente à mesure que l’événement est déclenché plus proche et le plus proche du domaine d’application par défaut, remplacez `e.Exception.Message` à `e.Exception` dans le `FirstChanceHandler` gestionnaires d’événements.</span><span class="sxs-lookup"><span data-stu-id="c2e36-113">To see how the stack display grows as the event is raised closer and closer to the default application domain, change `e.Exception.Message` to `e.Exception` in the `FirstChanceHandler` event handlers.</span></span> <span data-ttu-id="c2e36-114">Notez que lorsque `TestException` est appelée sur les limites du domaine d’application, il apparaît deux fois : une fois pour le proxy et une fois pour le stub.</span><span class="sxs-lookup"><span data-stu-id="c2e36-114">Notice that when `TestException` is called across application domain boundaries, it appears twice: once for the proxy and once for the stub.</span></span>  
  
 [!code-csharp[System.AppDomain.FirstChanceException#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/cs/example.cs#1)]
 [!code-vb[System.AppDomain.FirstChanceException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.appdomain.firstchanceexception/vb/example.vb#1)]  
  
 ]]></format>
    </remarks>
    <altmember cref="E:System.AppDomain.FirstChanceException" />
  </Docs>
  <Members>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public FirstChanceExceptionEventArgs (Exception exception);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(class System.Exception exception) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.#ctor(System.Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; FirstChanceExceptionEventArgs(Exception ^ exception);" />
      <MemberSignature Language="F#" Value="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs : Exception -&gt; System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" Usage="new System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs exception" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="exception" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="exception">
          <span data-ttu-id="c2e36-115">Exception qui vient d'être levée par du code managé et qui doit être examinée par l'événement <see cref="E:System.AppDomain.UnhandledException" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c2e36-115">The exception that was just thrown by managed code, and that will be examined by the <see cref="E:System.AppDomain.UnhandledException" /> event.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="c2e36-116">Initialise une nouvelle instance de la classe <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> avec l'exception spécifiée.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c2e36-116">Initializes a new instance of the <see cref="T:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs" /> class with a specified exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c2e36-117">Ce constructeur est appelé par le common language runtime, pas par le code d’application.</span><span class="sxs-lookup"><span data-stu-id="c2e36-117">This constructor is called by the common language runtime, not by application code.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Exception">
      <MemberSignature Language="C#" Value="public Exception Exception { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception Exception" />
      <MemberSignature Language="DocId" Value="P:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property Exception As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ Exception { Exception ^ get(); };" />
      <MemberSignature Language="F#" Value="member this.Exception : Exception" Usage="System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute FrameworkAlternate="netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0">
          <AttributeName>get: System.Runtime.ConstrainedExecution.ReliabilityContract(System.Runtime.ConstrainedExecution.Consistency.WillNotCorruptState, System.Runtime.ConstrainedExecution.Cer.Success)</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c2e36-118">Objet exception managé qui correspond à l'exception levée en code managé.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c2e36-118">The managed exception object that corresponds to the exception thrown in managed code.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c2e36-119">Exception qui vient d'être levée.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c2e36-119">The newly thrown exception.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c2e36-120">La méthode qui gère le <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> événement peut examiner l’exception et effectuer l’enregistrement approprié ou autres services de notification.</span><span class="sxs-lookup"><span data-stu-id="c2e36-120">The method that handles the <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> event can examine the exception and perform appropriate logging or other notification services.</span></span>  
  
 <span data-ttu-id="c2e36-121">Pour obtenir un exemple de code, consultez <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span><span class="sxs-lookup"><span data-stu-id="c2e36-121">For example code, see <xref:System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs>.</span></span>  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>