<Type Name="ThreadStartException" FullName="System.Threading.ThreadStartException">
  <TypeSignature Language="C#" Value="public sealed class ThreadStartException : SystemException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit ThreadStartException extends System.SystemException" />
  <TypeSignature Language="DocId" Value="T:System.Threading.ThreadStartException" />
  <TypeSignature Language="VB.NET" Value="Public NotInheritable Class ThreadStartException&#xA;Inherits SystemException" />
  <TypeSignature Language="C++ CLI" Value="public ref class ThreadStartException sealed : SystemException" />
  <AssemblyInfo>
    <AssemblyName>System.Threading.Thread</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
    <AssemblyVersion>4.1.1.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Exception</BaseTypeName>
    <BaseTypeName FrameworkAlternate="netframework-4.5">System.SystemException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary><span data-ttu-id="963da-101">Exception levée lorsqu'une erreur se produit dans un thread managé après le démarrage du thread de système d'exploitation sous-jacent, mais avant que le thread soit prêt à exécuter le code utilisateur.</span><span class="sxs-lookup"><span data-stu-id="963da-101">The exception that is thrown when a failure occurs in a managed thread after the underlying operating system thread has been started, but before the thread is ready to execute user code.</span></span></summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="963da-102">L’exception retournée par la <xref:System.Exception.InnerException%2A> propriété fournit des informations sur la raison de l’échec.</span><span class="sxs-lookup"><span data-stu-id="963da-102">The exception returned by the <xref:System.Exception.InnerException%2A> property provides information about the reason for the failure.</span></span>  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members />
</Type>